name: dev_container
channels:
- defaults
- esri
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - pip
  - pip:
    - azureml-defaults
    - azureml-pipeline-steps
    - streamlit
    - azure-storage-blob
    - joblib
    - sentence-transformers
    - faiss-cpu
    - datasets
    - azure-ai-ml
    - azure-identity
    - azure-keyvault-secrets
    #Milvus stuff
    - pymilvus
    #GCP stuf
    - google-cloud-aiplatform
    - google-cloud-storage
    - kfp
    - google-cloud-pipeline-components
    
