name: preprocess
channels:
- defaults
- esri
dependencies:
  - python=3.8
  - pip
  - pip:
    # - azureml-defaults
    # - azureml-pipeline-steps
    - joblib
    - sentence-transformers
    - numpy>=1.18.5
    - PyYAML>=5.3.1
    - torch>=1.7.0
    - torchvision>=0.8.1
    - pandas