# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

schedules:
  - cron: "0 6 * * 1-5"
    displayName: Morning Schedule
    branches:
      include:
        - main
    always: true

pr: none
trigger: none

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: CICD-sp

  # Web app name
  webAppName: 'semantic-search-streamlit'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  envName: semantic-search-streamlit

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)

  # Python version: 3.8
  pythonVersion: '3.8'

stages:
  - stage: Create_online_endpoint
    displayName: Deployments
    jobs:
      - deployment: endpoint
        pool: 
          vmImage: $(vmImageName)
        environment: $(envName)
        strategy:
          runOnce:
            deploy:              
              steps:
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '$(pythonVersion)'
                  displayName: 'Use Python $(pythonVersion)'
                - script: |
                    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
                    az extension add -n ml -y
                  workingDirectory: $(projectRoot)
                  displayName: "Install az ml extension"
                - checkout: self
                  path: 'SemanticSearch'
                - task: AzureCLI@2
                  displayName: Add deployment to online endpoint
                  inputs:
                    azureSubscription: $(azureServiceConnectionId)
                    scriptType: bash
                    scriptLocation: scriptPath
                    scriptPath: pipelines/online_endpoint/online_endpoint.sh
      # - deployment: webApp
      #   pool: 
      #     vmImage: $(vmImageName)
      #   environment: $(envName)
      #   strategy:
      #     runOnce:
      #       deploy:  
      #         steps:
      #           - task: UsePythonVersion@0
      #             inputs:
      #               versionSpec: '$(pythonVersion)'
      #             displayName: 'Use Python $(pythonVersion)'
      #           - script: |
      #               curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
      #               az extension add -n ml -y
      #             workingDirectory: $(projectRoot)
      #             displayName: "Install az ml extension"
      #           - checkout: self
      #             path: 'SemanticSearch'
      #           - task: AzureCLI@2
      #             displayName: Deploy webApp
      #             inputs:
      #               azureSubscription: $(azureServiceConnectionId)
      #               scriptType: bash
      #               scriptLocation: scriptPath
      #               scriptPath: pipelines/deploy_webapp.sh

