# Short client name which will be used throughout the project and in the making of azure resources
client_name: Covid

# deployment stages to be used in the project.
# Ideally dev, uat and prod are the only options to avoid problems
# packages.azureml_functions that assumes only these three stages are valid
deployment_stages:
  - dev
  - uat

# Language of the corpus -> controlls which models will be used to generate embeddings and to use for inference
corpus_language: English

# Path to the raw corpus in the default azure blob storage container, used in the preprocess pipeline
raw_corpus_path: raw_corpus

# Name of the bi and cross encoder model combo to be used for inference (Used in the deploy_backend)
bi_cross_encoder_name: bi_cross_encoders
# Version number of the bi and cross encoder model combo to be used for inference (Used in the deploy_backend)
bi_cross_encoder_version: 1

# Location where the embeddings dataset will be stored in the default azure blob storage container
# IMPORTANT that this is changed when experiments with new models or with training have been done, otherwise the embeddings will be overwritten
# Used in the deploy_backend and embedding_creator 
root: embeddings/basemodel/
# Pretty name for earch individual corpus used in the frontend
# location in the root folder where this corpus(with embeddings) will be stored (Used in the deploy_backend and score script)
corpora:
  - name: CORD-19 WHO
    location: WHO_cord_19