dutch:
  bi_encoder: "jegorkitskerkin/robbert-v2-dutch-base-mqa-finetuned" 
  cross_encoder: "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"
english:
  bi_encoder: "sentence-transformers/multi-qa-mpnet-base-dot-v1" 
  cross_encoder: "cross-encoder/ms-marco-MiniLM-L-6-v2"